apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-acopio
  labels:
    app: postgres-acopio
spec:
  selector:
    matchLabels:
      app: postgres-acopio
  template:
    metadata:
      labels:
        app: postgres-acopio
    spec:
      containers:
      - name: postgres-acopio
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "acopio"
        volumeMounts:
        - name: postgres-acopio-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-acopio-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-acopio-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-acopio-pv-claim
  labels:
    app: postgres-acopio
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-acopio
  labels:
    app: postgres-acopio
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-acopio
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: acopio-db
data:
  name: "acopio"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-proveedor
  labels:
    app: postgres-proveedor
spec:
  selector:
    matchLabels:
      app: postgres-proveedor
  template:
    metadata:
      labels:
        app: postgres-proveedor
    spec:
      containers:
      - name: postgres-proveedor
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "proveedor"
        volumeMounts:
        - name: postgres-proveedor-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-proveedor-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-proveedor-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-proveedor-pv-claim
  labels:
    app: postgres-proveedor
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-proveedor
  labels:
    app: postgres-proveedor
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-proveedor
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proveedor-db
data:
  name: "proveedor"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-laboratorio
  labels:
    app: postgres-laboratorio
spec:
  selector:
    matchLabels:
      app: postgres-laboratorio
  template:
    metadata:
      labels:
        app: postgres-laboratorio
    spec:
      containers:
      - name: postgres-laboratorio
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "laboratorio"
        volumeMounts:
        - name: postgres-laboratorio-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-laboratorio-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-laboratorio-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-laboratorio-pv-claim
  labels:
    app: postgres-laboratorio
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-laboratorio
  labels:
    app: postgres-laboratorio
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-laboratorio
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laboratorio-db
data:
  name: "laboratorio"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pago
  labels:
    app: postgres-pago
spec:
  selector:
    matchLabels:
      app: postgres-pago
  template:
    metadata:
      labels:
        app: postgres-pago
    spec:
      containers:
      - name: postgres-pago
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "pago"
        volumeMounts:
        - name: postgres-pago-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pago-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pago-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pago-pv-claim
  labels:
    app: postgres-pago
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-pago
  labels:
    app: postgres-pago
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-pago
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pago-db
data:
  name: "pago"