server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: acopio-service
          uri: lb://acopio-service
          predicates:
            - Path=/acopio/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedor/**
        - id: laboratorio-service
          uri: lb://laboratorio-service
          predicates:
            - Path=/laboratorio/**
	- id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/pago/**