server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/amigo1975/microsevices-data-project
	  username: $jnramirezm
	  password: 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
          search-paths: config-data
  application:
    name: config-service
